name: wonder_tool
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+13

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.2.1
  badges: ^2.0.3
  stop_watch_timer: ^1.5.0
  flutter_svg: ^1.1.1+1
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_charts: ^20.2.36
  youtube_player_flutter: ^8.1.0
  like_button: ^2.0.4
  shimmer: ^2.0.0
  flutter_unity_widget: ^2022.3.0-alpha1
  html_editor_enhanced: ^2.5.0
  pull_to_refresh: ^2.0.0
  flutter_html: ^3.0.0-alpha.5
  flutter_html_table: ^3.0.0-alpha.3
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  url_launcher: ^6.1.4
  syncfusion_flutter_barcodes: ^20.2.36
  flutter_slidable: ^1.3.0
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  carousel_slider: ^4.1.1
  flutter_local_notifications: ^9.7.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  package_info_plus:
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launch.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.otf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
